### ISSUE TITLE
Add support for requirements to be satisfied by AP credits, summer courses, study abroad, etc.

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#101]
Add support for requirements to be satisfied by AP credits, as well as courses taken during the summer or during study abroad.

Similarly, allow users to mark that they have received a waiver for a requirement.

**Comment by bnehoran** [comment]
Additional question: If we allow force completion of a requirement, would we allow partial force completion?
For example, if you need 4 of a particular requirement, then could a user say that they already have 1, and then the app only requires 3 more using courses in their schedule?

**Comment by churichard** [comment]
Yes, I think we should allow partial force completion. For example, for COS, I only satisfied one systems course when I studied abroad, but I need two systems courses for that subrequirement.

**Comment by bnehoran** [comment]
**Here's the proposal:**
We add a 9th semester to the user course schedule, which will now contain the pseudo-courses that are manually added by the user with custom names.
These will always be added as "settled" courses, with the `settled` field being populated with the path to the requirement they satisfy.
If done right, the pseudo-course will automatically be added by the verifier to the right place in the requirements tree, and will appear as if it were just another course, but with the user's custom name.

Here are the steps we need to take:

- [ ] Add another pseudo-semester to the user schedule in the database, and ensure that the app only ever reads off the 8 real semesters everywhere else in the app, including the GUI. Check that this doesn't break any functionality. 
- [ ] Pass the now 9-semester schedule to the verifier as input and check that this doesn't break anything, that it still works as intended. I think the only modification needed here to get this to work is to remove any sanity checks for no more than 8 semesters, if these exist in the code.
- [ ] On the GUI side, add a button to each req popover that says something like "Add external or AP credit". When pressed, this should bring up a popup with a text field allowing the user to enter a name for the class, and an explanation/warning that this course will be added only to this req, and without any verification that it actually satisfies the req.
- [ ] When a user fills in this text field and submits, the app should add a pseudo-course, with the user-defined title and the path to the req from which it originated as its `settled` field, to the user's extra pseudo-semester, and then send a new request to refresh the req tree.


Two additional things we need to consider:
- Should the extra semester be at the beginning of the list, in position 0, or at the end, in position 8? Which one makes more sense, and which one would make the conventions simpler and modifications easier?
- What sort of validation do we need from the user-defined titles? Allowing a user to enter arbitrary text is always a source for extra caution. I don't think it will cause any security concerns, since we are only ever treating the input as a string value. However, the naive implementation could cause weird results if the user enters the code for an existing class, in that this class could also start satisfying other requirements. This is not necessarily that big a deal, and it may very well be harmless, but I just want to bring it up.

**Comment by churichard** [comment]
Been pretty busy the past few days, so I only got the chance to respond now.

I think your proposal makes sense and seems like a clean way to do this. Some thoughts about your additional questions:

1. It would probably be easiest to add the extra semester to the end of the list, at position 8. I know in the frontend we have some logic related to iterating through the semesters, and adding the extra semester at the end rather than the beginning simplifies this iteration a bit. The only consideration that I might have about adding it to the end is it might make it more difficult to add support for more than 8 semesters in the future if we ever choose to do that. But since that isn't currently on the roadmap and I don't anticipate it to be, I think it's fine.
2. If the user input is always treated as a string, then security won't be an issue. I suppose the job of making sure that if the user types in, say, "COS 126" as their pseudo-course, that it doesn't satisfy any other requirements other than the user-specified one, seems like it should be in the verifier. I'll leave that up to you :)
