### ISSUE TITLE
Extend database subscription

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#131]

**Comment by churichard** [comment]
Done. I created a new DigitalOcean account with free credits and transferred the droplets that I had in my other account to the new one. This will extend our database life for another 60 days, after which we will hopefully have demonstrated enough traction to get sponsored by TigerApps.

Note that everyone will have to update their dev database credentials in order to continue with development, as I've shut down the old databases. The new credentials are available in the Heroku config vars for tigerpath333-dev, under DATABASE_URL. Make sure you don't accidentally use the production database for development.
