### ISSUE TITLE
TigerSnatch direct links in SearchCard and Popover components

### ISSUE THREAD

**Issue by nicholaspad** [TigerAppsOrg/TigerPath#409]
Currently, SearchCard and Popover components contain a direct link to PrincetonCourses via a blue "i" icon:

| SearchCard | Popover |
|------------|---------|
|      ![image](https://user-images.githubusercontent.com/13815069/123744495-b4b42980-d863-11eb-9d95-adc8d3ddd5cb.png) |     ![image](https://user-images.githubusercontent.com/13815069/123744064-10ca7e00-d863-11eb-82db-715bebfd91d2.png)    |

I'd like to add a second icon to the left of the above icon that links directly to [TigerSnatch](https://snatch.tigerapps.org), a platform that enables students to get notified when slots open up in full courses. TigerSnatch is a new TigerApp, and it replaced PrincetonPounce. I was one of the developers of TigerSnatch and am one of its maintainers as part of being on the TigerApps team.

For example, it might look like this in a SearchCard component:

![image](https://user-images.githubusercontent.com/13815069/123744400-92baa700-d863-11eb-89b5-484f2ae7e9af.png)

and clicking on the hourglass would link to this page: https://snatch.tigerapps.org/course?courseid=002051. An identical icon would be placed in the same place in a Popover component.

I have already implemented a similar change in both PrincetonCourses (example: https://www.princetoncourses.com/course/1222002051 in the upper right) and in ReCal (https://recal.io, the clock icon revealed by hovering over a search result or a saved course on the left).

I have already committed this feature to my fork of TigerPath, but I'm not sure how to test it because I don't have access to the database or the staging site (if you have one). Let me know if you'd like me to push my code to a new dev branch in the main repo.

**Comment by nicholaspad** [comment]
@churichard

**Comment by churichard** [comment]
Hey Nick! Thanks for opening up this feature request. After thinking about it, I don't believe we should add a link to TigerSnatch in TigerPath.

The purpose of TigerPath is, first and foremost, to help Princeton students plan out their long-term course schedules. Everything that is in TigerPath is intended to contribute to this goal. For example, the requirements pane helps students know what requirements they've fulfilled and what they still need to fulfill in order to graduate on time. The link to Princeton Courses also helps in this goal by providing more information about courses so that they can make an informed decision about what courses they want to take.

TigerSnatch is different in this regard; it's focused instead on the logistics of taking courses, namely trying to get into the courses that you want. It operates on a different time scale from TigerPath; you will only ever use TigerSnatch for courses in the current semester, but TigerPath shows all semesters. And while students might check TigerPath any time during the school year, there are only a few weeks where TigerSnatch would be useful to use.

Ultimately, I don't think it makes sense to add a permanent link to TigerSnatch in TigerPath, especially if there are already links in both Recal and Princeton Courses (both of which are tools students would likely already be using as they plan for the current semester). That being said, I think TigerSnatch looks like a fantastic and useful tool, and I wish you the best of luck with it :)

**Comment by nicholaspad** [comment]
That makes total sense! TigerPath is meant to be a long-term planning tool, while TigerSnatch, Princeton Courses, and Recal are meant to help plan for the upcoming/current semester. Regardless, thanks for considering the feature :)
